# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2016-06-26 22:45
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0012_queue_default_owner'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customfield',
            managers=[
                ('objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='followup',
            managers=[
                ('objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
