# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2016-06-29 02:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0013_auto_20160627_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='enabled',
            field=models.BooleanField(default=True, help_text='No tickets can be created on disabled queues, but tickets can be looked up & edited', verbose_name='Enable queue'),
        ),
    ]
