# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-19 20:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0015_auto_20170127_0421'),
        ('helpdesk', '0016_alter_model_options'),
    ]

    operations = [
    ]
