# Generated by Django 2.2.15 on 2024-01-10 14:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('helpdesk', '0018_add_coms_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='signed_by',
            field=models.ManyToManyField(blank=True, related_name='requisitions_signed', to=settings.AUTH_USER_MODEL, verbose_name='Signed by'),
        ),
    ]
