# Generated by Django 2.2.17 on 2020-11-14 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0018_fix_migrations'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='o365_client_id',
            field=models.CharField(blank=True, help_text='If using Office 365, enter your client ID', max_length=200, null=True, verbose_name='Office 365 Client ID'),
        ),
        migrations.AddField(
            model_name='queue',
            name='o365_client_secret',
            field=models.CharField(blank=True, help_text='If using Office 365, enter your client secret', max_length=200, null=True, verbose_name='Office 365 Client Secret'),
        ),
        migrations.AddField(
            model_name='queue',
            name='o365_tenant_id',
            field=models.CharField(blank=True, help_text='If using Office 365, enter your tenant ID', max_length=200, null=True, verbose_name='Office 365 Tenant ID'),
        ),
        migrations.AlterField(
            model_name='queue',
            name='email_box_type',
            field=models.CharField(blank=True, choices=[('pop3', 'POP 3'), ('imap', 'IMAP'), ('local', 'Local Directory'), ('o365', 'Office 365 API')], help_text='E-Mail server type for creating tickets automatically from a mailbox - both POP3 and IMAP are supported, as well as reading from a local directory or reading from the Office 365 API.', max_length=5, null=True, verbose_name='E-Mail Box Type'),
        ),
    ]
