# Generated by Django 2.0.7 on 2018-07-17 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0019_auto_20180709_1841'),
        ('helpdesk', '0019_auto_20180717_1522'),
    ]

    operations = [
    ]
