# Generated by Django 2.2.17 on 2020-11-14 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0019_auto_20201114_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='o365_resource_mailbox',
            field=models.CharField(blank=True, help_text='If using Office 365, enter the resource mailbox', max_length=200, null=True, verbose_name='Office 365 Resource Mailbox'),
        ),
    ]
