# Generated by Django 2.2.13 on 2020-06-22 15:28

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0019_ticket_customer_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='contact_phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='numéro de téléphone'),
        ),
    ]
