# Generated by Django 2.2.17 on 2020-11-14 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0020_queue_o365_resource_mailbox'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='o365_mailbox_folder',
            field=models.CharField(blank=True, help_text="If using Office 365, enter the name of the folder in the resource mailbox. Defaults to 'Inbox'.", max_length=200, null=True, verbose_name='Office 365 Mailbox folder'),
        ),
    ]
