# Generated by Django 2.2.13 on 2020-06-23 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_spenttime'),
        ('helpdesk', '0020_ticket_contact_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketSpentTime',
            fields=[
                ('spenttime_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.SpentTime')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spent_times', to='helpdesk.Ticket')),
            ],
            options={
                'verbose_name': 'Temps passé sur un ticket',
                'verbose_name_plural': 'Temps passés sur un ticket',
            },
            bases=('base.spenttime',),
        ),
    ]
