# Generated by Django 2.2.17 on 2020-11-14 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0021_queue_o365_mailbox_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='send_through_o365',
            field=models.BooleanField(blank=True, default=False, help_text='Do you want emails relating to this queue to be sent through Office 365?', verbose_name='Send emails through Office 365?'),
        ),
    ]
