# Generated by Django 2.2.13 on 2020-06-24 15:01

from django.db import migrations, models
import django.db.models.deletion


def populate(apps, schema_editor):
    TicketCategory = apps.get_model('helpdesk', 'TicketCategory')
    db_alias = schema_editor.connection.alias
    TicketCategory.objects.using(db_alias).bulk_create([
        TicketCategory(name="Cloud"),
        TicketCategory(name="Data"),
        TicketCategory(name="Développement"),
        TicketCategory(name="Hébergement"),
        TicketCategory(name="IPBX"),
        TicketCategory(name="Mobile"),
        TicketCategory(name="Téléphone / Borne / Passerelle"),
        TicketCategory(name="Trunk / T0 / T2"),
    ])


def unpopulate(apps, schema_editor):
    TicketCategory = apps.get_model('helpdesk', 'TicketCategory')
    db_alias = schema_editor.connection.alias
    TicketCategory.objects.using(db_alias).get(name="Cloud").delete()
    TicketCategory.objects.using(db_alias).get(name="Data").delete()
    TicketCategory.objects.using(db_alias).get(name="Développement").delete()
    TicketCategory.objects.using(db_alias).get(name="Hébergement").delete()
    TicketCategory.objects.using(db_alias).get(name="IPBX").delete()
    TicketCategory.objects.using(db_alias).get(name="Mobile").delete()
    TicketCategory.objects.using(db_alias).get(name="Téléphone / Borne / Passerelle").delete()
    TicketCategory.objects.using(db_alias).get(name="Trunk / T0 / T2").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0021_ticketspenttime'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='nom', unique=True)),
            ],
            options={
                'verbose_name': 'Catégorie ticket',
                'verbose_name_plural': 'Catégories ticket',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='ticket',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='helpdesk.TicketCategory', verbose_name='catégorie'),
        ),
        migrations.RunPython(populate, unpopulate)
    ]
