# Generated by Django 2.2.13 on 2020-06-24 15:54

from django.db import migrations, models
import django.db.models.deletion


def populate(apps, schema_editor):
    TicketType = apps.get_model('helpdesk', 'TicketType')
    db_alias = schema_editor.connection.alias
    TicketType.objects.using(db_alias).bulk_create([
        TicketType(name="Incident"),
        TicketType(name="Modification", mandatory_facturation=True),
        TicketType(name="Demande d’informations"),
        TicketType(name="Queue de chantier"),
        TicketType(name="Interne"),
    ])


def unpopulate(apps, schema_editor):
    TicketType = apps.get_model('helpdesk', 'TicketType')
    db_alias = schema_editor.connection.alias
    TicketType.objects.using(db_alias).get(name="Incident").delete()
    TicketType.objects.using(db_alias).get(name="Modification", mandatory_facturation=True).delete()
    TicketType.objects.using(db_alias).get(name="Demande d’informations").delete()
    TicketType.objects.using(db_alias).get(name="Queue de chantier").delete()
    TicketType.objects.using(db_alias).get(name="Interne").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0022_auto_20200624_1701'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='nom')),
                ('mandatory_facturation', models.BooleanField(default=False, verbose_name='facturation obligatoire')),
            ],
            options={
                'verbose_name': 'Type ticket',
                'verbose_name_plural': 'Types ticket',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='ticket',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='helpdesk.TicketType'),
        ),
        migrations.RunPython(populate, unpopulate)
    ]
