# Generated by Django 2.2.17 on 2021-02-14 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0022_queue_send_through_o365'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='hash',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
