# Generated by Django 2.2.13 on 2020-06-25 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0024_ticket_billing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='billing',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Contrat de maintenance'), (2, 'Carnet de jeton'), (3, 'Devis'), (4, 'Offert'), (5, 'Facturation à tort')], null=True, verbose_name='facturation'),
        ),
    ]
