# Generated by Django 2.2.13 on 2020-07-08 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0025_auto_20200625_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='quick_comment',
            field=models.CharField(blank=True, max_length=200, verbose_name='commentaire rapide'),
        ),
    ]
