# Generated by Django 2.2.13 on 2020-07-28 07:48

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0026_ticket_quick_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followup',
            name='comment',
            field=tinymce.models.HTMLField(blank=True, default='', verbose_name='Comment'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='presetreply',
            name='body',
            field=tinymce.models.HTMLField(help_text='Context available: {{ ticket }} - ticket object (eg {{ ticket.title }}); {{ queue }} - The queue; and {{ user }} - the current user.', verbose_name='Body'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='description',
            field=tinymce.models.HTMLField(blank=True, default='', help_text='The content of the customers query.', verbose_name='Description'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ticket',
            name='resolution',
            field=tinymce.models.HTMLField(blank=True, default='', help_text='The resolution provided to the customer by our staff.', verbose_name='Resolution'),
            preserve_default=False,
        ),
    ]
