# Generated by Django 2.2.9 on 2020-01-27 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pinax_teams', '0004_auto_20170511_0856'),
        ('helpdesk', '0027_auto_20200107_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='kbitem',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pinax_teams.Team', verbose_name='Team'),
        ),
    ]
