# Generated by Django 2.2.13 on 2020-08-07 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0027_auto_20200728_0948'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='merged_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='merged_tickets', to='helpdesk.Ticket', verbose_name='fusionné à'),
        ),
    ]
