# Generated by Django 2.2.13 on 2020-09-25 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0028_ticket_merged_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='resolved',
            field=models.DateTimeField(blank=True, help_text='Date this ticket was resolved', null=True, verbose_name='Resolved'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='closed',
            field=models.DateTimeField(blank=True, help_text='Date this ticket was closed', null=True, verbose_name='Closed'),
        ),
    ]
