# Generated by Django 2.2.13 on 2020-10-09 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0029_ticket_closed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='followup',
            options={'ordering': ('-date',), 'verbose_name': 'Follow-up', 'verbose_name_plural': 'Follow-ups'},
        ),
    ]
