# Generated by Django 2.2.13 on 2020-10-14 14:51

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0030_auto_20201009_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='numéro de téléphone'),
        ),
    ]
