# Generated by Django 2.2.13 on 2020-11-16 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0032_feedbacksurvey'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TicketSpentTime',
        ),
    ]
