# Generated by Django 2.2.13 on 2020-12-21 13:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0033_delete_ticketspenttime'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenericIncident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='date de dernière modification')),
                ('name', models.CharField(max_length=100, verbose_name='nom')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date de début')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='date de fin')),
                ('description', models.TextField(blank=True)),
                ('external_link', models.URLField(blank=True, verbose_name='lien externe')),
                ('intervention_report', models.FileField(blank=True, upload_to='intervention_reports/%Y/%m/', verbose_name="rapport d'intervention")),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='helpdesk.TicketCategory', verbose_name='catégorie')),
            ],
            options={
                'verbose_name': 'Incident Générique',
                'verbose_name_plural': 'Incidents Génériques',
            },
        ),
    ]
