# Generated by Django 2.2.13 on 2021-01-04 17:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('helpdesk', '0035_ticket_generic_incident'),
    ]

    operations = [
        migrations.AddField(
            model_name='genericincident',
            name='subscribers',
            field=models.ManyToManyField(blank=True, help_text='List of people who wish to receive updates about this generic incident', to=settings.AUTH_USER_MODEL, verbose_name='abonnés'),
        ),
    ]
