# Generated by Django 2.2.13 on 2021-06-10 19:50

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.utils.timezone

class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0035_form'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Form',
            new_name='FormType',
        ),
        migrations.AlterModelOptions(
            name='formtype',
            options={'get_latest_by': 'created', 'ordering': ('id',)},
        ),
        migrations.RenameField(
            model_name='formtype',
            old_name='organization_id',
            new_name='organization',
        ),
        migrations.AlterField(
            model_name='formtype',
            name='created',
            field=models.DateTimeField(auto_now_add=True)
        ),
        migrations.AlterField(
            model_name='formtype',
            name='updated',
            field=models.DateTimeField(auto_now=True)
        ),
    ]
