# Generated by Django 2.2.13 on 2021-06-11 14:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0037_auto_20210610_1326'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customfield',
            old_name='name',
            new_name='field_name',
        ),
        migrations.AddField(
            model_name='customfield',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customfield',
            name='field_name',
            field=models.SlugField(default='default', help_text='As used in the database and behind the scenes. Must consist of only lowercase letters with no punctuation.', verbose_name='Field Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customfield',
            name='form_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='helpdesk.FormType'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customfield',
            name='is_extra_data',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customfield',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='customfield',
            name='label',
            field=models.CharField(blank=True, help_text='The display label for this field', max_length=200, null=True, verbose_name='Label'),
        ),
        migrations.AlterUniqueTogether(
            name='customfield',
            unique_together=set([('field_name', 'form_type')]),
        ),
    ]
