# Generated by Django 2.2.13 on 2021-06-24 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0038_auto_20210611_0750'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customfield',
            options={'ordering': ['form_ordering'], 'verbose_name': 'Custom field', 'verbose_name_plural': 'Custom fields'},
        ),
        migrations.RenameField(
            model_name='customfield',
            old_name='form_type',
            new_name='ticket_form',
        ),
        migrations.AddField(
            model_name='customfield',
            name='editable',
            field=models.BooleanField(default=True, help_text='Can this field be edited by a staff user?', verbose_name='Editable by staff?'),
        ),
        migrations.AddField(
            model_name='customfield',
            name='form_ordering',
            field=models.IntegerField(blank=True, help_text='Order of fields when submitting a form. Lower numbers are displayed first; higher numbers are listed later', null=True, verbose_name='Form Ordering'),
        ),
        migrations.AddField(
            model_name='customfield',
            name='unlisted',
            field=models.BooleanField(default=False, help_text='Used for default fields like queue and priority.', verbose_name='Is this field represented another way on the ticket view?'),
        ),
        migrations.AddField(
            model_name='customfield',
            name='view_ordering',
            field=models.IntegerField(blank=True, help_text='Order of fields when viewing a ticket. Lower numbers are displayed first; higher numbers are listed later', null=True, verbose_name='View Ordering'),
        ),
        migrations.AlterField(
            model_name='customfield',
            name='data_type',
            field=models.CharField(blank=True, choices=[('varchar', 'Character (single line)'), ('text', 'Text (multi-line)'), ('integer', 'Integer'), ('decimal', 'Decimal'), ('list', 'List'), ('boolean', 'Boolean (checkbox yes/no)'), ('date', 'Date'), ('time', 'Time'), ('datetime', 'Date & Time'), ('email', 'E-Mail Address'), ('url', 'URL'), ('ipaddress', 'IP Address'), ('slug', 'Slug')], help_text='Allows you to restrict the data entered into this field', max_length=100, null=True, verbose_name='Data Type'),
        ),
        migrations.AlterUniqueTogether(
            name='customfield',
            unique_together={('field_name', 'ticket_form')},
        ),
        migrations.RemoveField(
            model_name='customfield',
            name='ordering',
        ),
    ]
