# Generated by Django 5.0.2 on 2024-07-22 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0038_checklist_checklisttemplate_checklisttask'),
    ]

    operations = [
        migrations.AddField(
            model_name='followup',
            name='extra_fields',
            field=models.JSONField(blank=True, null=True, verbose_name='Extra Fields'),
        ),
    ]
