# Generated by Django 2.2.13 on 2021-07-01 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0039_auto_20210624_0921'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customfield',
            options={'ordering': ['ticket_form', 'form_ordering'], 'verbose_name': 'Custom field', 'verbose_name_plural': 'Custom fields'},
        ),
        migrations.AlterField(
            model_name='formtype',
            name='description',
            field=models.TextField(blank=True, help_text='Introduction text included in the form.', null=True),
        ),
        migrations.AlterField(
            model_name='formtype',
            name='extra_data',
            field=models.JSONField(blank=True, default=list, help_text='List of CustomField field_names that belong to this form. Format: ["field_name1", "field_name2"]'),
        ),
    ]
