# Generated by Django 2.2.13 on 2021-07-14 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0040_auto_20210701_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='kbcategory',
            name='preview_description',
            field=models.TextField(blank=True, null=True, verbose_name='Preview description on knowledgebase page'),
        ),
        migrations.AlterField(
            model_name='kbcategory',
            name='description',
            field=models.TextField(verbose_name='Full description on knowledgebase category page'),
        ),
    ]
