# Generated by Django 2.2.13 on 2021-08-26 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0041_auto_20210714_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='formtype',
            name='public',
            field=models.BooleanField(blank=True, default=True, help_text='Should this form be visible on the public-side list of forms?', verbose_name='Public'),
        ),
        migrations.AddField(
            model_name='formtype',
            name='queue',
            field=models.ForeignKey(blank=True, help_text='Tickets should automatically be added to this queue.This option will hide the Queue field on the form.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='helpdesk.Queue'),
        ),
        migrations.AddField(
            model_name='formtype',
            name='staff',
            field=models.BooleanField(blank=True, default=True, help_text='Should this form be visible on the staff-side list of forms?', verbose_name='Staff'),
        ),
    ]
