# Generated by Django 2.2.13 on 2021-09-20 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0042_auto_20210826_0701'),
    ]

    operations = [
        migrations.AddField(
            model_name='customfield',
            name='notifications',
            field=models.BooleanField(default=False, help_text='Only for Email Address: adds this email to the list of addresses that receive notifications of ticket updates. By default, only submitter_email and contact_email receive notifications.', verbose_name='Use this email for notifications?'),
        ),
    ]
