# Generated by Django 2.2.13 on 2021-10-25 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0043_customfield_notifications'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customfield',
            options={'ordering': ['ticket_form', 'form_ordering'], 'verbose_name': 'Form field', 'verbose_name_plural': 'Form fields'},
        ),
        migrations.AlterModelOptions(
            name='formtype',
            options={'get_latest_by': 'created', 'ordering': ('id',), 'verbose_name': 'Form', 'verbose_name_plural': 'Forms'},
        ),
        migrations.AlterModelOptions(
            name='kbcategory',
            options={'ordering': ('title',), 'verbose_name': 'Knowledgebase category', 'verbose_name_plural': 'Knowledgebase categories'},
        ),
        migrations.AlterModelOptions(
            name='kbitem',
            options={'ordering': ('order', 'title'), 'verbose_name': 'Knowledgebase article', 'verbose_name_plural': 'Knowledgebase articles'},
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='organization',
        ),
        migrations.AlterField(
            model_name='customfield',
            name='is_extra_data',
            field=models.BooleanField(default=True, help_text='Is this an extra data field?', verbose_name='Non-default field?'),
        ),
        migrations.AlterField(
            model_name='customfield',
            name='unlisted',
            field=models.BooleanField(default=False, help_text='Used for default fields like queue and priority, which are displayed elsewhere.', verbose_name='Hide field in view table?'),
        ),
        migrations.AlterField(
            model_name='kbiattachment',
            name='kbitem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helpdesk.KBItem', verbose_name='Knowledgebase Article'),
        ),
        migrations.AlterField(
            model_name='kbitem',
            name='answer',
            field=models.TextField(help_text='<a href="http://daringfireball.net/projects/markdown/syntax" target="_blank">Markdown syntax</a> allowed, but no raw HTML. Examples: **bold**, *italic*, indent 4 spaces for a code block.<br/><br/>To add a collapsing section: Add !~! on a line following the section title, followed by a blank line. Add ~!~ on a line following the section body, followed by another blank line. <br/>The body may have multiple lines of text, but no blank lines.<br/><br/>Example:<div style="margin-left: 40px;">This text comes before the section.<br/><br/>Title of Subsection<br/>!~!<br/><br/>Body of subsection.<br/>I can add many lines of text to this. It will all be included in the section.<br/>~!~<br/><br/>This, however, won\'t be included in the collapsing section.</div>', verbose_name='Answer'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='building_id',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Building ID'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='pm_id',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Portfolio Manager ID'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='helpdesk.FormType'),
        ),
    ]
