# Generated by Django 2.2.13 on 2021-10-26 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0044_auto_20211025_1214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formtype',
            name='extra_data',
        ),
    ]
