# Generated by Django 2.2.13 on 2021-11-12 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0015_auto_20211112_1406'),
        ('helpdesk', '0045_remove_formtype_extra_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='orgs.Organization'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='followup',
            name='new_status',
            field=models.IntegerField(blank=True, choices=[(1, 'Open'), (2, 'Reopened'), (3, 'Resolved'), (4, 'Closed'), (5, 'Duplicate'), (6, 'Replied')], help_text='If the status was changed, what was it changed to?', null=True, verbose_name='New Status'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.IntegerField(choices=[(1, 'Open'), (2, 'Reopened'), (3, 'Resolved'), (4, 'Closed'), (5, 'Duplicate'), (6, 'Replied')], default=1, verbose_name='Status'),
        ),
    ]
