# Generated by Django 2.2.13 on 2021-10-26 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0147_merge_beam01'),
        ('helpdesk', '0045_remove_formtype_extra_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='customfield',
            name='columns',
            field=models.ManyToManyField(blank=True, related_name='helpdesk_fields', to='seed.Column', verbose_name='Associated BEAM columns'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='beam_property',
            field=models.ManyToManyField(blank=True, related_name='helpdesk_ticket', to='seed.Property', verbose_name='BEAM Property'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='beam_taxlot',
            field=models.ManyToManyField(blank=True, related_name='helpdesk_ticket', to='seed.TaxLot', verbose_name='BEAM Taxlot'),
        ),
    ]
