# Generated by Django 2.2.13 on 2021-12-07 20:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('helpdesk', '0047_auto_20211124_0855'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedsearch',
            name='opted_out_users',
            field=models.ManyToManyField(blank=True, help_text='Users who have opted out of seeing this query', related_name='opted_out', to=settings.AUTH_USER_MODEL),
        ),
    ]
