# Generated by Django 3.2.7 on 2021-12-22 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0048_auto_20211222_0706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='extra_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
