# Generated by Django 2.2.13 on 2021-12-09 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0022_auto_20211130_1216'),
        ('helpdesk', '0048_savedsearch_opted_out_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='kbcategory',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='orgs.Organization'),
            preserve_default=False,
        ),
    ]
