# Generated by Django 3.2.7 on 2022-01-18 18:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orgs', '0022_auto_20211130_1216'),
        ('helpdesk', '0049_alter_ticket_extra_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='kbcategory',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='orgs.organization'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='savedsearch',
            name='opted_out_users',
            field=models.ManyToManyField(blank=True, help_text='Users who have opted out of seeing this query', related_name='opted_out', to=settings.AUTH_USER_MODEL),
        ),
    ]
