# Generated by Django 3.2.7 on 2022-05-06 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0177_auto_20220506_1226'),
        ('helpdesk', '0055_auto_20220506_1237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='queue',
            name='email_address',
        ),
        migrations.RemoveField(
            model_name='queue',
            name='email_box_host',
        ),
        migrations.RemoveField(
            model_name='queue',
            name='email_box_imap_folder',
        ),
        migrations.RemoveField(
            model_name='queue',
            name='email_box_local_dir',
        ),
        migrations.RemoveField(
            model_name='queue',
            name='email_box_pass',
        ),
        migrations.RemoveField(
            model_name='queue',
            name='email_box_port',
        ),
        migrations.RemoveField(
            model_name='queue',
            name='email_box_ssl',
        ),
        migrations.RemoveField(
            model_name='queue',
            name='email_box_type',
        ),
        migrations.RemoveField(
            model_name='queue',
            name='email_box_user',
        ),
        migrations.RemoveField(
            model_name='queue',
            name='locale',
        ),
        migrations.RemoveField(
            model_name='queue',
            name='logging_dir',
        ),
        migrations.RemoveField(
            model_name='queue',
            name='logging_type',
        ),
        migrations.RemoveField(
            model_name='queue',
            name='permission_name',
        ),
        migrations.RemoveField(
            model_name='queue',
            name='socks_proxy_host',
        ),
        migrations.RemoveField(
            model_name='queue',
            name='socks_proxy_port',
        ),
        migrations.RemoveField(
            model_name='queue',
            name='socks_proxy_type',
        ),
        migrations.RemoveField(
            model_name='queue',
            name='email_box_interval',
        ),
        migrations.RemoveField(
            model_name='queue',
            name='email_box_last_check',
        ),
        migrations.RemoveField(
            model_name='queue',
            name='keep_mail',
        ),
    ]
