# Generated by Django 3.2.7 on 2022-05-13 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0179_auto_20220513_1348'),
        ('helpdesk', '0056_auto_20220506_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='ignoreemail',
            name='importers',
            field=models.ManyToManyField(blank=True, help_text='Leave blank for this e-mail to be ignored on all importer emails, or select those importers you wish to ignore this e-mail for.', to='seed.EmailImporter'),
        ),
    ]
