# Generated by Django 3.2.7 on 2022-05-13 20:54

from django.db import migrations


def assign_ignored_emails(apps, schema_editor):
    # Not at all optimized, but it's fine for a one-time migration
    IgnoreEmail = apps.get_model('helpdesk', 'IgnoreEmail')
    for ignored in IgnoreEmail.objects.all():
        for queue in ignored.queues.all():
            if queue.importer:
                ignored.importers.add(queue.importer)
        ignored.save()  # just in case


def revert_ignored_emails(apps, schema_editor):
    IgnoreEmail = apps.get_model('helpdesk', 'IgnoreEmail')
    for ignored in IgnoreEmail.objects.all():
        for importer in ignored.importers.all():
            for queue in importer.queue_set.all():
                ignored.queues.add(queue)
        ignored.save()  # just in case


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0057_auto_20220513_1308'),
    ]

    operations = [
        migrations.RunPython(assign_ignored_emails, revert_ignored_emails),
    ]
