# Generated by Django 3.2.7 on 2022-05-13 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0058_auto_20220513_1354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ignoreemail',
            name='queues',
        ),
    ]
