# Generated by Django 3.2.7 on 2022-05-16 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0059_remove_ignoreemail_queues'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='match_on_addresses',
            field=models.JSONField(blank=True, default=list, help_text="A list of strings. If you'd like only emails from specific addresses to be imported into this queue, list those addresses here. Otherwise, leave blank."),
        ),
    ]
