# Generated by Django 3.2.7 on 2022-05-23 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0060_queue_match_on_addresses'),
        ('seed', '0181_auto_20220523_0818'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='importer_sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='seed.importersendermapping'),
        ),
    ]

