# Generated by Django 3.2.7 on 2022-05-23 15:21

from django.db import migrations


def combine_importer_senders(apps, schema_editor):
    Queue = apps.get_model('helpdesk', 'Queue')
    ImporterSenderMapping = apps.get_model('seed', 'ImporterSenderMapping')
    for queue in Queue.objects.all():
        if getattr(queue, 'importer', False) and getattr(queue, 'sender', False):
            importer = ImporterSenderMapping.objects.filter(importer=queue.importer)
            sender = ImporterSenderMapping.objects.filter(sender=queue.sender)
            if not importer and not sender:
                default_queue = None if not queue.importer.default_queue else queue.importer.default_queue
                importer_sender = ImporterSenderMapping.objects.create(
                    sender=queue.sender,
                    importer=queue.importer,
                    default_queue=default_queue,
                )
                queue.importer_sender = importer_sender
                queue.save()
            else:
                try:
                    importer_sender = ImporterSenderMapping.objects.filter(sender=queue.sender, importer=queue.importer)
                except ImporterSenderMapping.DoesNotExist:
                    if sender:
                        queue.importer_sender = sender
                    elif importer:
                        queue.importer_sender = importer
                else:
                    importer_sender = importer_sender.first()
                    queue.importer_sender = importer_sender
                queue.save()


def recreate_importer_senders(apps, schema_editor):
    Queue = apps.get_model('helpdesk', 'Queue')
    ImporterSenderMapping = apps.get_model('seed', 'ImporterSenderMapping')
    for queue in Queue.objects.all():
        if getattr(queue, 'importer_sender', False):
            queue.importer = queue.importer_sender.importer
            queue.sender = queue.importer_sender.sender
            queue.save()
    for importer_sender in ImporterSenderMapping.objects.all():
        if getattr(importer_sender, 'default_queue', False):
            importer = importer_sender.importer
            importer.default_queue = importer_sender.default_queue
            importer.save()


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0061_auto_20220523_0818'),
        ('seed', '0181_auto_20220523_0818'),
    ]

    operations = [
        migrations.RunPython(combine_importer_senders, recreate_importer_senders),
    ]
