# Generated by Django 3.2.7 on 2022-05-23 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0062_auto_20220523_0821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='queue',
            name='importer',
        ),
        migrations.RemoveField(
            model_name='queue',
            name='sender',
        ),
    ]
