# Generated by Django 3.2.7 on 2022-06-06 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0039_rename_sender_email_address_organization_sender'),
        ('helpdesk', '0063_auto_20220523_0822'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orgs.organization'),
        ),
        migrations.AlterField(
            model_name='queue',
            name='allow_email_submission',
            field=models.BooleanField(blank=True, default=False, help_text='Turn on or off email imports for queues with match lists only. Does not affect default queues, or follow-up imports.', verbose_name='Turn on E-Mail Imports?'),
        ),
    ]
