# Generated by Django 3.2.7 on 2022-06-06 15:54

from django.db import migrations


def add_org_to_template(apps, schema_editor):
    Organization = apps.get_model('orgs', 'Organization')
    EmailTemplate = apps.get_model('helpdesk', 'EmailTemplate')
    org = Organization.objects.order_by('id').first()
    if org:
        for template in EmailTemplate.objects.all():
            if not template.organization:
                template.organization = org
                template.save()


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0064_auto_20220606_0852'),
        ('orgs', '0039_rename_sender_email_address_organization_sender'),
    ]

    operations = [
        migrations.RunPython(add_org_to_template, migrations.RunPython.noop)
    ]
