# Generated by Django 3.2.7 on 2022-06-09 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0066_auto_20220607_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followup',
            name='new_status',
            field=models.IntegerField(blank=True, choices=[(1, 'Open'), (2, 'Reopened'), (3, 'Resolved'), (4, 'Closed'), (5, 'Duplicate'), (6, 'Replied'), (7, 'New')], help_text='If the status was changed, what was it changed to?', null=True, verbose_name='New Status'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.IntegerField(choices=[(1, 'Open'), (2, 'Reopened'), (3, 'Resolved'), (4, 'Closed'), (5, 'Duplicate'), (6, 'Replied'), (7, 'New')], default=7, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='queue',
            name='reassign_when_closed',
            field=models.BooleanField(default=False, help_text='When a ticket is closed, reassign the ticket to the default owner (if one is set).'),
        ),
    ]
