# Generated by Django 3.2.12 on 2022-07-22 16:23

from django.db import migrations, models


def re_add_fields(apps, schema_editor):
    CustomField = apps.get_model('helpdesk', 'CustomField')
    fields = CustomField.objects.all()
    for field in fields:
        if field.field_name not in ['queue', 'submitter_email', 'contact_name', 'contact_email', 'title',
                                    'description', 'building_name', 'building_address', 'building_id', 'pm_id',
                                    'attachment', 'due_date', 'priority', 'cc_emails']:
            field.is_extra_data = False

        if field.field_name in ['queue', 'submitter_email', 'title', 'description', 'attachment', 'due_date', 'priority', 'cc_emails']:
            field.unlisted = True

        if field.field_name in ['attachment', 'cc_emails']:
            field.editable = False

        field.save()


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0067_auto_20220609_1308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customfield',
            name='is_extra_data',
        ),
        migrations.RemoveField(
            model_name='customfield',
            name='unlisted',
        ),
        migrations.RemoveField(
            model_name='customfield',
            name='editable',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='title',
            field=models.CharField(default='(no title)', max_length=200),
        ),
        migrations.RunPython(migrations.RunPython.noop, re_add_fields)
    ]
