# Generated by Django 3.2.12 on 2022-07-22 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0067_auto_20220609_1308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customfield',
            name='is_extra_data',
        ),
        migrations.RemoveField(
            model_name='customfield',
            name='unlisted',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='title',
            field=models.CharField(default='(no title)', max_length=200),
        ),
    ]
