# Generated by Django 3.2.12 on 2022-08-10 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0068_auto_20220722_0923'),
    ]

    operations = [
        migrations.AddField(
            model_name='customfield',
            name='public',
            field=models.BooleanField(default=True, verbose_name='Show on public form?'),
        ),
        migrations.AddField(
            model_name='customfield',
            name='staff',
            field=models.BooleanField(default=True, verbose_name='Show on staff form?'),
        ),
    ]
