# Generated by Django 3.2.12 on 2022-08-17 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0070_migrate_staff_only_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customfield',
            name='staff_only',
        ),
    ]
