# Generated by Django 3.2.12 on 2022-09-14 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0198_move_importer_data'),
        ('helpdesk', '0071_remove_staff_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='importer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='seed.emailimporter'),
        ),
    ]
