# Generated by Django 3.2.12 on 2022-09-14 18:19

from django.db import migrations


def move_importer_data(apps, schema_editor):
    Queue = apps.get_model('helpdesk', 'Queue')
    for queue in Queue.objects.filter(importer_sender__isnull=False):
        queue.importer = queue.importer_sender.importer
        queue.save()


def move_importer_data_back(apps, schema_editor):
    Queue = apps.get_model('helpdesk', 'Queue')
    for queue in Queue.objects.filter(importer__isnull=False):
        queue.importer_sender = queue.importer.importersendermapping_set.first()
        queue.save()


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0072_queue_importer'),
    ]

    operations = [
        migrations.RunPython(move_importer_data, move_importer_data_back)
    ]
