# Generated by Django 3.2.12 on 2022-09-14 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0073_move_queue_importers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='queue',
            name='importer_sender',
        ),
    ]
