# Generated by Django 3.2.12 on 2022-10-21 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0074_remove_queue_importersender'),
    ]

    operations = [
        migrations.AddField(
            model_name='formtype',
            name='unlisted',
            field=models.BooleanField(default=False, help_text='Should this form be hidden from the public form list? (It will still be accessible by everyone if the "public" option is checked.)', verbose_name='Unlisted'),
        ),
        migrations.AlterField(
            model_name='formtype',
            name='public',
            field=models.BooleanField(blank=True, default=True, help_text='Should this form be accessible by everyone?', verbose_name='Public'),
        ),
        migrations.AlterField(
            model_name='formtype',
            name='staff',
            field=models.BooleanField(blank=True, default=True, help_text='Should this form be only accessible by staff? It will not be shown in the public form list.', verbose_name='Staff'),
        ),
    ]
