# Generated by Django 3.2.12 on 2023-02-16 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0076_alter_customfield_data_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='kbcategory',
            name='forms',
            field=models.ManyToManyField(blank=True, help_text='Forms listed on the page, that the user can submit after reading any article in this category. (Only public forms will be displayed to public users, regardless of whether or not they are unlisted.)', to='helpdesk.FormType'),
        ),
    ]
