# Generated by Django 3.2.18 on 2023-05-23 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0217_alter_emailtemplate_tags'),
        ('helpdesk', '0077_kbcategory_forms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customfield',
            name='columns',
        ),
        migrations.AddField(
            model_name='customfield',
            name='column',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='helpdesk_fields', to='seed.column', verbose_name='Associated BEAM column'),
        ),
    ]
