# Generated by Django 3.2.18 on 2023-06-21 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0078_update_customfield_column'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formtype',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
