# Generated by Django 3.2.18 on 2023-06-21 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0078_update_customfield_column'),
    ]

    operations = [
        migrations.AddField(
            model_name='customfield',
            name='lookup',
            field=models.BooleanField(default=False, help_text='Use the value in this field to pair tickets with BEAM properties/taxlots?', verbose_name='Use for BEAM pairings?'),
        ),
    ]
