# Generated by Django 3.2.18 on 2023-07-06 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0080_alter_formtype_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customfield',
            name='list_values_json',
            field=models.JSONField(blank=True, default=list, help_text='For list fields only. Enter one option per line.', null=True, verbose_name='List Values'),
        ),
    ]
