# Generated by Django 3.2.18 on 2023-07-06 18:27

from django.db import migrations

def transfer_list_values(apps, schema_editor):
    CustomField = apps.get_model("helpdesk", "CustomField")
    for cf in CustomField.objects.all():
        if cf.list_values and cf.list_values != "[]":
            cf.list_values_json = cf.list_values.split()
        else:
            cf.list_values_json = None
        cf.save()

class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0081_customfield_list_values_json'),
    ]

    operations = [
        migrations.RunPython(transfer_list_values)
    ]
