# Generated by Django 3.2.18 on 2023-07-06 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0083_remove_customfield_list_values'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customfield',
            old_name='list_values_json',
            new_name='list_values',
        ),
    ]
