# Generated by Django 3.2.18 on 2023-07-18 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0086_alter_markdown_helptext'),
    ]

    operations = [
        migrations.AddField(
            model_name='kbcategory',
            name='form_submission_text',
            field=models.CharField(default='Ask a question about this article', max_length=250, verbose_name='Form submission button text'),
        ),
        migrations.AddField(
            model_name='kbitem',
            name='forms',
            field=models.ManyToManyField(blank=True, help_text='The list of forms that visitors will be able to use to submit a ticket after reading this article. This selection will override forms chosen for the category.<br/>To deselect a form, hold down Ctrl or Cmd and click on the form.<br/>Only public forms will be displayed to public visitors, regardless of whether or not they are unlisted.', to='helpdesk.FormType'),
        ),
        migrations.AlterField(
            model_name='kbcategory',
            name='forms',
            field=models.ManyToManyField(blank=True, help_text='The list of forms that visitors will be able to use to submit a ticket after reading an article in this category.<br/>To deselect a form, hold down Ctrl or Cmd and click on the form.<br/>Only public forms will be displayed to public visitors, regardless of whether or not they are unlisted.', to='helpdesk.FormType'),
        ),
    ]
