# Generated by Django 3.2.18 on 2023-07-19 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0087_alter_kb_forms'),
    ]

    operations = [
        migrations.AddField(
            model_name='ignoreemail',
            name='queues',
            field=models.ManyToManyField(blank=True, help_text='Leave blank for this e-mail to be ignored on all queue emails, or select those queues you wish to ignore this e-mail for.', to='helpdesk.Queue'),
        ),
        migrations.AddField(
            model_name='ignoreemail',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.deletion.CASCADE, to='orgs.organization'),
        ),
        migrations.AddField(
            model_name='ignoreemail',
            name='modified',
            field=models.DateField(blank=True, null=True, default=None, editable=False, help_text='Date on which this e-mail address was last modified', verbose_name='Last Modified'),
        ),
        migrations.AlterField(
            model_name='ignoreemail',
            name='email_address',
            field=models.CharField(help_text='Enter a full e-mail address, or portions with wildcards, eg *@domain.com or postmaster@*.', max_length=150, verbose_name='Email Address'),
        ),
    ]
