# Generated by Django 3.2.18 on 2023-07-19 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0045_merge_beam03'),
        ('helpdesk', '0090_remove_ignoreemail_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='presetreply',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orgs.organization'),
        ),
        migrations.AlterField(
            model_name='ignoreemail',
            name='email_address',
            field=models.CharField(help_text='Enter a full e-mail address, or portions with wildcards, eg *@domain.com or postmaster@*.', max_length=150, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='ignoreemail',
            name='modified',
            field=models.DateField(blank=True, default=None, editable=False, help_text='Date on which this e-mail address was last modified', verbose_name='Last Modified'),
        ),
    ]
