# Generated by Django 3.2.18 on 2023-07-20 18:56

from django.db import migrations


def add_orgs_to_replies(apps, schema_editor):
    PreSetReply = apps.get_model('helpdesk', 'PreSetReply')
    Organization = apps.get_model('orgs', 'Organization')
    for reply in PreSetReply.objects.filter(queues__isnull=False):
        reply.organization = reply.queues.first().organization
        reply.save()
        reply.queues.set(reply.queues.filter(organization=reply.organization))
    for reply in PreSetReply.objects.filter(queues__isnull=True):
        reply.organization = Organization.objects.first().helpdesk_organization
        reply.save()


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0091_add_presetreply_organization'),
    ]

    operations = [
        migrations.RunPython(add_orgs_to_replies, migrations.RunPython.noop),
    ]
