# Generated by Django 3.2.18 on 2023-08-23 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0093_alter_presetreply_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='ignoreemail',
            name='ignore_import',
            field=models.BooleanField(default=False, help_text='If checked, emails sent from this address will not be created as tickets.', verbose_name='Ignore imports from this?'),
        ),
        migrations.AddField(
            model_name='ignoreemail',
            name='prevent_send',
            field=models.BooleanField(default=True, help_text='If checked, emails from Helpdesk will not be sent to this address.', verbose_name='Prevent sending to this?'),
        ),
    ]
