# Generated by Django 3.2.18 on 2023-10-25 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0047_auto_20230821_1529'),
        ('helpdesk', '0094_auto_20230823_1211'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('color', models.CharField(choices=[('danger', 'red'), ('warning', 'orange'), ('success', 'green'), ('info', 'light blue'), ('primary', 'blue'), ('secondary', 'gray')], default='success', max_length=30)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orgs.organization')),
            ],
        ),
        migrations.AddField(
            model_name='ticket',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tickets', to='helpdesk.Tag'),
        ),
    ]
