# Generated by Django 3.2.18 on 2023-11-14 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0095_ticket_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='allow_sending',
            field=models.BooleanField(default=True),
        ),
    ]
