# Generated by Django 3.2.18 on 2024-05-29 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0097_alter_customfield_data_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kbcategory',
            options={'ordering': ('order', 'title'), 'verbose_name': 'Knowledgebase category', 'verbose_name_plural': 'Knowledgebase categories'},
        ),
        migrations.AddField(
            model_name='kbcategory',
            name='order',
            field=models.PositiveIntegerField(blank=True, help_text='Smaller numbers will be ordered first.', null=True, verbose_name='Ordering'),
        ),
    ]
