# Generated by Django 3.2.18 on 2024-05-30 17:09

from django.db import migrations

def move_to_TimeSpent(apps, schema_editor):
    FollowUp = apps.get_model('helpdesk', 'FollowUp')
    TimeSpent = apps.get_model('helpdesk', 'TimeSpent')

    for followup in FollowUp.objects.all():
        if followup.user:
            user = followup.user
        else:
            user = None
        
        ticket = followup.ticket
        start_time = followup.date
        stop_time = start_time
        if followup.time_spent:
            stop_time += followup.time_spent
        

        TimeSpent.objects.create(
            user = user,
            ticket = ticket,
            start_time = start_time,
            stop_time = stop_time,
            followup = followup,
        )



class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0099_add_timespent_model'),
    ]

    operations = [
        migrations.RunPython(move_to_TimeSpent)
    ]
