# Generated by Django 3.2.18 on 2024-06-04 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0100_move_followup_timespent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followup',
            name='time_spent',
        ),
    ]
