# Generated by Django 3.2.18 on 2024-06-04 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0101_remove_followup_time_spent'),
    ]

    operations = [
        migrations.AddField(
            model_name='kbitem',
            name='unlisted',
            field=models.BooleanField(default=False, help_text='Should this form be hidden from the public article list? (If the "Is this article publicly accessible?" option is checked, this form will still be accessible by everyone through the link.)', verbose_name='Unlisted'),
        ),
        migrations.AlterField(
            model_name='kbitem',
            name='enabled',
            field=models.BooleanField(default=True, verbose_name='Is this article publicly accessible?'),
        ),
    ]
