# Generated by Django 3.2.20 on 2024-09-17 14:17

from django.db import migrations, models, transaction
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0061_add_org_backgroundimage'),
        ('helpdesk', '0102_add_kbitem_unlisted'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedsearch',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orgs.organization', verbose_name='Organization'),
        ),
    ]
