# Generated by Django 3.2.20 on 2024-09-17 14:17

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0061_add_org_backgroundimage'),
        ('helpdesk', '0104_copy_savedsearch_to_all_orgs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedsearch',
            name='organization',
            field=models.ForeignKey(null=False, on_delete=django.db.models.deletion.CASCADE, to='orgs.organization', verbose_name='Organization')
        )
    ]
