# Generated by Django 5.2.16 on 2026-08-19 22:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("helpdesk", "0039_alter_ticketchange_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="followup",
            name="email_recipients",
            field=models.JSONField(
                blank=True,
                default=None,
                help_text="Addresses successfully notified by e-mail about this follow-up. Null means recipients were not recorded.",
                null=True,
                verbose_name="E-Mail Recipients",
            ),
        ),
    ]
