# Generated by Django 6.0.7 on 2026-08-28 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0040_followup_email_recipients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='Date this ticket was first created', verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='Date this ticket was most recently changed.', verbose_name='Modified'),
        ),
    ]
