# Generated by Django 6.0.8 on 2026-09-23 19:22

import helpdesk.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("helpdesk", "0041_alter_ticket_created_alter_ticket_modified"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersettings",
            name="ticket_respond_layout",
            field=models.CharField(
                choices=[
                    ("tabs", "Tabs: follow ups and respond share a tabbed card"),
                    ("bottom", "Respond form below the follow ups"),
                    ("top", "Respond form above the follow ups"),
                ],
                default=helpdesk.models.ticket_respond_layout_default,
                help_text="Where should the respond form appear when viewing a ticket?",
                max_length=16,
                verbose_name="Ticket respond form layout",
            ),
        ),
    ]
