# Generated by Django 6.0.9 on 2026-10-09 16:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

from helpdesk import settings as helpdesk_settings


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0042_usersettings_ticket_respond_layout'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ] + helpdesk_settings.HELPDESK_TEAMS_MIGRATION_DEPENDENCIES

    operations = [
        migrations.AlterField(
            model_name='followup',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='kbitem',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=helpdesk_settings.HELPDESK_TEAMS_MODEL, verbose_name='Team'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_to', to=settings.AUTH_USER_MODEL, verbose_name='Assigned to'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='merged_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merged_tickets', to='helpdesk.ticket', verbose_name='merged to'),
        ),
    ]